server:
  port: 8888
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.53.63:3306/wx_shop?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: xiaomili200816
    hikari:
      max-lifetime: 1000000
  thymeleaf:
    cache: false #关闭缓存
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:  #引用这个是解决 Spring boot 2.6使用Swagger2提示“documentationPluginsBootstrapper”错误
    pathmatch:
      matching-strategy: ant_path_matcher

#devtools:
#  restart:
#    enabled: true #设置开启热部署
#    additional-paths: src/main/java #重启目录

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vno.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

authority:
  info: '[]'

logging:
  file:
    path: log
    name: log/my.log
  level:
    com:
      javaclimb:
        dao: debug
