package com.vno.entity;

import javax.persistence.*;

/**
 * Database Table Remarks:
 *   文件信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table nx_system_file_info
 */
@Table(name = "nx_system_file_info")
public class NxSystemFileInfo {
    /**
     *   主键
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     *   原始文件名
     */
    @Column(name = "originname")
    private String originname;

    /**
     *   存储文件名
     */
    @Column(name = "filename")
    private String filename;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOriginname() {
        return originname;
    }

    public void setOriginname(String originname) {
        this.originname = originname == null ? null : originname.trim();
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }
}